// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: register_oom_snapshot_template.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const registerOOMSnapshotTemplate = `-- name: RegisterOOMSnapshotTemplate :one
WITH new_env AS (
    INSERT INTO "public"."envs" (id, public, created_by, team_id, updated_at, source)
    VALUES ($1, FALSE, NULL, $2, now(), 'snapshot_template')
    RETURNING id
),

new_snapshot_template AS (
    INSERT INTO "public"."snapshot_templates" (env_id, sandbox_id, origin_node_id, build_id)
    VALUES (
        (SELECT id FROM new_env),
        $3,
        $4,
        $5
    )
),

new_build AS (
    INSERT INTO "public"."env_builds" (
        id, vcpu, ram_mb, free_disk_size_mb, total_disk_size_mb,
        kernel_version, firecracker_version, envd_version,
        status, cluster_node_id, env_id, finished_at, updated_at
    ) VALUES (
        $5, $6, $7, $8, $9,
        $10, $11, $12,
        'success', $4, (SELECT id FROM new_env), now(), now()
    )
    RETURNING id
),

build_assignment AS (
    INSERT INTO "public"."env_build_assignments" (env_id, build_id, tag)
    VALUES (
        (SELECT id FROM new_env),
        (SELECT id FROM new_build),
        $13
    )
    RETURNING env_id
)

SELECT env_id FROM build_assignment
`

type RegisterOOMSnapshotTemplateParams struct {
	TemplateID         string
	TeamID             uuid.UUID
	SandboxID          string
	OriginNodeID       *string
	BuildID            *uuid.UUID
	Vcpu               int64
	RamMb              int64
	FreeDiskSizeMb     int64
	TotalDiskSizeMb    *int64
	KernelVersion      string
	FirecrackerVersion string
	EnvdVersion        *string
	Tag                string
}

// Atomically registers an OOM-rescue snapshot as a snapshot_template.
// Build files are already in GCS under build_id (orchestrator wrote them
// via snapshotAndCacheSandbox + uploadSnapshotAsync); this query writes
// the four DB tables that make the build resolvable as a SDK template:
//
//	envs                      (source = 'snapshot_template')
//	snapshot_templates        (env_id → sandbox_id, build_id, origin_node_id)
//	env_builds                (id = supplied build_id, status = success)
//	env_build_assignments     (env_id, build_id, tag)
//
// After this query, SDK Sandbox.create("<env_id>:<tag>") starts a new
// sandbox from the OOM-rescue snapshot.
func (q *Queries) RegisterOOMSnapshotTemplate(ctx context.Context, arg RegisterOOMSnapshotTemplateParams) (string, error) {
	row := q.db.QueryRow(ctx, registerOOMSnapshotTemplate,
		arg.TemplateID,
		arg.TeamID,
		arg.SandboxID,
		arg.OriginNodeID,
		arg.BuildID,
		arg.Vcpu,
		arg.RamMb,
		arg.FreeDiskSizeMb,
		arg.TotalDiskSizeMb,
		arg.KernelVersion,
		arg.FirecrackerVersion,
		arg.EnvdVersion,
		arg.Tag,
	)
	var env_id string
	err := row.Scan(&env_id)
	return env_id, err
}
